config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "homes/about" => "homes#about", as: "about"
  resources :post_images, only: [:new,:create,:index,:show,:destroy]
  # get 'post_images/new'
  # get 'post_images/index'
  # get 'post_images/show'
  
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
  resource :favorites, only: [:create, :destroy]
    # 単数形にすると、/:idがURLに含まれなくなる
  resources :post_comments, only: [:create, :destroy]
  end
  # 投稿画像に対してコメントされるため、post_commentsは、post_imagesに結びつく
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # Favoriteモデルのカラム（user_idとpost_image_id）は、UserモデルのidやPostImageモデルのidと関連付ける
  # いいね機能は１：NのN側
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  # UserモデルもPostImageモデルも、PostCommentに関連付けられるのは1つだけ
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  
  belongs_to :user
  # belongs_to : 「〜に属する」アソシエーション
  #PostImage モデルから user_id に関連付けられていて、User モデルを参照することができる 
  # 1:N の「N」側にあたるモデルに、belongs_to を記載する
  # 1 つの User モデルに関連付けられるため、単数形の「user」にする
  
  has_many :post_comments, dependent: :destroy
  # PostCommentモデルを複数持つ 
  
  has_many :favorites, dependent: :destroy
  
  validates :shop_name, presence: true
  validates :image, presence: true
  # バリテーション：入力されたデータのpresence（存在）をチェック
  
  # 画像が存在しない場合に表示する画像をActiveStorageに格納する
  def get_image
    unless image.attached?
       file_path=Rails.root.join('app/assets/images/no_image.jpg')
       image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image
  end
  # get_image ...メソッド（アクションではない）
  # PostImageモデル内に記載して、カラムを呼び出すように、このメソッドをよびだせる

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  # favorited_by?メソッドで、引数で渡されたユーザidがFavoritesテーブル内に
  # 存在（exists?）するかどうかを調べる
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
# deviseを利用したユーザーテーブルの作成
# deviceとは、ユーザー認証機能を有したGem(パッケージ）
# 作成した User モデルに devise で使用する機能が記述されている        

# :database_authenticatable（パスワードの正確性を検証）
# :registerable（ユーザ登録や編集、削除）
# :recoverable（パスワードをリセット）
# :rememberable（ログイン情報を保存）
# :validatable（email のフォーマットなどのバリデーション）

  has_many :post_images, dependent: :destroy 
# has_many : 「post＿imagesをたくさん持っている」
# 「１：Nの関係」の１側のモデルに記載する
# dependent: :destroy : 1:Nの1側が削除されたとき、N側を全て削除する
#   依存    :  削除

 has_many :post_comments, dependent: :destroy
 
 has_many :favorites, dependent: :destroy

  has_one_attached :profile_image
# profile_imageという名前でActiveStorageでプロフィール画像を保存できるように設定
  
  def get_profile_image(width, height)
  # 画像が登録されていない場合のエラー回避
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
      #画像サイズの変更 　
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  # バリテーション
  # :authenticate_user!：ログイン認証されていなければ、ログイン画面へリダイレクトする
  # except：トップページのみログイン状態に関わらず、アクセス可能
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_actionメソッド：コントローラーで各アクションを実行する前に実行したい処理を指定することができる
  
  def after_sign_in_path_for(resource)
    post_images_path
  # after_sign_in_path_for: Deviseが用意しているメソッドで、
  # サインイン後にどこに遷移するかを設定しているメソッド
  end
  
  def after_sign_out_path_for(resource)
    about_path
    # after_sign_out_path_for: Deviseが用意しているメソッドで
    # サインアウト後にどこに遷移するかを設定するメソッド
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  # configure_permitted_parametersメソッド：devise_parameter_sanitizer.permitメソッドを使うことで
  # ユーザー登録(sign_up)の際に、ユーザー名(name)のデータ操作を許可する
  # permit...保存を許可するカラムを指定します
  
  
  # deviseのコントローラは直接修正できないため、ApplicationControllerに記述する
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
# いいね機能は投稿画像の詳細画面（/post_images/:id/）で実装
  def create
     post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
      post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    # コメント作成し、データベースに保存する
    post_image = PostImage.find(params[:post_image_id])
    # アソシエーションしたPostImageモデルの idを、post_image_idとして取得する
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end
  
  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    # 画像投稿の画面を表示する
    @post_image=PostImage.new
  end

  def create
    # 投稿データを保存する
    @post_image=PostImage.new(post_image_params)
    # post_image_params : フォームで入力されたデータが、投稿データとして許可されているパラメータかどうかをチェック
    # フォームに入力されたデータが、インスタンス変数に格納される
    @post_image.user_id=current_user.id
    # user_idは、画像投稿を行う際に、投稿したユーザーをユーザーの ID で判断する
    # @post_image.user_id: PostImage モデルに紐づくカラムの値を取得したり、逆に値を代入することができる
    # current_user : ログイン中のユーザー情報を取得することができる
    # @post_image(投稿データ)のuser_idを、current_user.id(今ログインしているユーザーの ID)に
    # 指定することで投稿データに、今ログイン中のユーザーの ID を持たせることができる
    
    if @post_image.save
      redirect_to post_images_path
      # もし対象のカラムにデータが保存されたら、投稿一覧画面へリダイレクト
    else
      render :new
    end
  end

  def index
    # タイムライン上に表示する全ての画像を取得する
    # @post_images=PostImage.all
    
     @post_images = PostImage.page(params[:page])
    # 1ページ分の決められた数のデータだけを、新しい順に取得する
    # pageメソッド:kaminariをインストールしたことで使用可能になったメソッド
  end

  def show
    # 詳細画面
    @post_image=PostImage.find(params[:id])
    # コメントを投稿する
    @post_comment=PostComment.new
  end
  
  def destroy
    post_image=PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
    # 投稿の削除後は一覧画面に遷移
  end

  # 投稿データのストロングパラメータ
  private
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
# before_actionメソッド：コントローラーで各アクションを実行する前に実行したい処理を指定することができる
  
  def show
    @user=User.find(params[:id])
    # idに関連付けられているUserモデルのレコード全てを取得する
    @post_images = @user.post_images.page(params[:page])
    # 特定のユーザ（@user）に関連付けられた投稿を、決められた分だけ（.post_images）を取得
    # @post_imagesに渡す という処理を行う
  end

  def edit 
    @user=User.find(params[:id])
    # 「params[:id]」：URLに含まれる:idを取得できる
  end
  
  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
aboutページ

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <!--stylesheet_pack_tag：app/javascript 配下のファイルを参照する-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

    <!--全てのhtmlに共通するヘッダー-->
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %> 
    <!--devise 側で用意しているヘルパーメソッド-->
    <!--ログインしている時としていない時で表示を分ける-->
      <li>
        <!--投稿フォームへのリンク-->
        <%= link_to '投稿フォーム', new_post_image_path %>
      </li>
      <li>
        <!--マイページへのリンク-->
        <%= link_to 'マイページ', user_path(current_user.id) %>
      </li>
     
      <li>
        <!--ログイン済みの場合にブラウザに表示-->
        <%= link_to "ログアウト", destroy_user_session_path,method: :delete %>
      </li>
    <% else %> 
        <!--ログインしていない場合にブラウザに表示-->
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
       </ul>
          </div>
        </div>
      </nav>
  </header>
    <%= yield %>
   </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/_list.html.erb
<!--部分テンプレート-->
<!--ファイル名にアンダースコア＿つける

<!--ユーザーの詳細画面と、投稿画像の一覧画面-->

<div class="card-list-container py-5">
<% post_images.each do |post_image| %>
<!--post_imagesはローカル変数-->
  <div class="card w-50 mx-auto mt-4 shadow-lg">
  <!--link_toでは、doからendの間が、aタグで囲まれた状態。 結果、image_tagは、aタグに囲まれたimgタグになる-->
    <%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image, class:"card-img-top"; %>
    <% end %>
  <!--image_tagを使い、post_imageにActiveStorageで設定したimageを表示する-->
  <!--post_image.get_image : PostImageモデル内に記述したメソッドを呼び出している-->
  
 <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

<!--「card」class-->
<!--「card」classには以降の子要素で使用するclassが依存する
<!--その中の要素で使用するものは自由に組むことができる-->

app/views/post_images/index.html.erb
<!--一覧ページ-->
<!--部分テンプレートの呼び出し-->
 
<%=  render 'list', post_images: @post_images %>

<!--render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] -->

<!--同じフォルダ内にある場合はフォルダ名と拡張子は省略できる-->
<!--部分テンプレートのローカル変数に渡すインスタンス変数を指定する-->

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>

<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <!--画面幅が切り替わったときに、入力フォームの幅などを調節するためにcolを二つ指定-->
    <!--複数のcolをブレークポイントごとに指定することで画面幅に応じたレイアウトを提供-->
    <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">

<% if @post_image.errors.any? %>
<!--errors：モデルにバリデーションをかけたときに、発生したエラーの内容を確認できるメソッド-->
<!--any?と組み合わせることで、エラーが発生しているかどうかを判定-->
    <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

<%= form_with model: @post_image do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
<!--form_with を利用して、post_images_path/post_imagesに画像をアップロード-->
<div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<!--画像の詳細画面-->

<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>投稿ユーザー画像：<%= image_tag 'sample-author1.jpg' %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <!--投稿日付の形式を変換しているメソッド-->
  <!--'%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換-->
  
 <% if @post_image.user==current_user %>
 <!--もし画像の投稿ユーザーが、ログインしているユーザーだったら-->
  <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <%end%>
  
    <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
    <% end %>
    </p>
  <% end %>
  </div>
  
  <!--投稿画像の詳細画面で、コメントも投稿できるようにする-->
  <div>
    <p>コメント件数：<%= @post_image.post_comments.count %></p>
    <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
  </div>
  
  <div>
   <%= form_with model: [@post_image, @post_comment] do |f| %>
  <!--コメントは、post_imageに結びついたpost_commentであるため、2つ用意する必要あり-->
  <!--post_commentをcreateするためのリクエストは、ルーティングもネストしているため、上記2つの情報が必要-->
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<!--ユーザーの詳細ページ-->

<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user == current_user %>
  <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <%end%>
  <!--ログインしているユーザーに本人のみ、編集リンクを表示させる-->
<!--画面に表示しているユーザーと、ログインしているユーザーのIDが一致するか確認-->
</div>

<!--ユーザーの投稿一覧画面-->
<!--部分テンプレート-->

<%= render 'post_images/list', post_images: @post_images %>
<!--post_imagesフォルダ内から呼び出す、違うフォルダから呼ぶときはフォルダ名も指定する-->